### PR TITLE
Fixing build error when using mapped_futures

### PR DESCRIPTION
**Pull request by Meisterian**
This Monday; I wasn't able to import mapped_futures anymore (0.1.12). The following build error occurs while building mapped_futures:

```
   Compiling tokio-rustls v0.25.0
   Compiling mapped_futures v0.1.12
   Compiling rumqttc v0.24.0
error[E0310]: the parameter type `K` may not live long enough
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mapped_futures-0.1.12/src/mapped_futures/task.rs:104:9
    |
104 |         waker_ref(this)
    |         ^^^^^^^^^^^^^^^
    |         |
    |         the parameter type `K` must be valid for the static lifetime...
    |         ...so that the type `K` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
101 | impl<K: Hash + Eq + 'static, Fut> Task<K, Fut> {
    |                   +++++++++

error[E0310]: the parameter type `Fut` may not live long enough
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mapped_futures-0.1.12/src/mapped_futures/task.rs:104:9
    |
104 |         waker_ref(this)
    |         ^^^^^^^^^^^^^^^
    |         |
    |         the parameter type `Fut` must be valid for the static lifetime...
    |         ...so that the type `Fut` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
101 | impl<K: Hash + Eq, Fut: 'static> Task<K, Fut> {
    |                       +++++++++

   Compiling protobuf-codegen v3.6.0
For more information about this error, try `rustc --explain E0310`.
error: could not compile `mapped_futures` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

I'm a C++ developer and quite new to rust, but I'm posting my patch anyway.

Regards,
Christian

### CODE REVIEW

**Comment by StoicDeveloper** [comment]
Thanks for notifying me! I am not able to replicate this problem though. What version of rustc are you using? I am hesitant to merge this PR, because in adding the 'static trait bound, it means that this library would become unusable for projects that use key or future types that include non-static references. So if there is a different way to solve this problem that that would be ideal. It should be possible, since the original library, FuturesUnordered, which this library modifies, does not use static trait bounds.

**Comment by StoicDeveloper** [comment]
When you use FuturesUnordered, does the same compilation error arise?

**Comment by Meisterian** [comment]
FuturesUnordered works fine. I use mapped futures for timeouts that I want to be able to cancel.
As I said; I'm quite new to rust, so it might be my fault...

[build-dependencies]
protobuf-codegen = "3.6.0"

[dev-dependencies]
mockall = "0.13.0"

```
[dependencies]
bytes = "1.7.2"
clap = "4.5.20"
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
mapped_futures = "0.1.12"
protobuf = "3.6.0"
regex = "1.10.6"
rumqttc = "0.24.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
uuid = { version = "1.10.0", features = ["v4"] }
[target.'cfg(target_os = "linux")'.dependencies]
systemd = "0.10.0"
```

```
$ rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
```

```
cargo build
    Updating crates.io index
  Downloaded build-env v0.3.1
  Downloaded anstyle-query v1.1.1
  Downloaded anstyle v1.0.8
  Downloaded openssl-probe v0.1.5
  Downloaded untrusted v0.9.0
  Downloaded which v4.4.2
  Downloaded pkg-config v0.3.31
  Downloaded anstream v0.6.15
  Downloaded equivalent v1.0.1
  Downloaded autocfg v1.4.0
  Downloaded once_cell v1.20.2
  Downloaded colorchoice v1.0.2
  Downloaded clap_lex v0.7.2
  Downloaded cstr-argument v0.1.2
  Downloaded pin-project-lite v0.2.14
  Downloaded serde v1.0.210
  Downloaded cfg-if v1.0.0
  Downloaded parking_lot_core v0.9.10
  Downloaded protobuf-support v3.6.0
  Downloaded fastrand v2.1.1
  Downloaded quote v1.0.37
  Downloaded rustls-pki-types v1.9.0
  Downloaded futures-channel v0.3.31
  Downloaded scopeguard v1.2.0
  Downloaded errno v0.3.9
  Downloaded foreign-types-shared v0.3.1
  Downloaded cc v1.1.28
  Downloaded futures-macro v0.3.31
  Downloaded log v0.4.22
  Downloaded foreign-types v0.5.0
  Downloaded signal-hook v0.3.17
  Downloaded futures-executor v0.3.31
  Downloaded lock_api v0.4.12
  Downloaded bytes v1.7.2
  Downloaded pin-utils v0.1.0
  Downloaded parking_lot v0.12.3
  Downloaded anyhow v1.0.89
  Downloaded is_terminal_polyfill v1.70.1
  Downloaded futures-task v0.3.31
  Downloaded utf8parse v0.2.2
  Downloaded thiserror v1.0.64
  Downloaded signal-hook-mio v0.2.4
  Downloaded shlex v1.3.0
  Downloaded either v1.13.0
  Downloaded subtle v2.6.1
  Downloaded memchr v2.7.4
  Downloaded futures-sink v0.3.31
  Downloaded itoa v1.0.11
  Downloaded home v0.5.9
  Downloaded futures-io v0.3.31
  Downloaded bisetmap v0.1.6
  Downloaded utf8-cstr v0.1.6
  Downloaded foreign-types-macros v0.2.3
  Downloaded futures-core v0.3.31
  Downloaded futures v0.3.31
  Downloaded zeroize v1.8.1
  Downloaded getrandom v0.2.15
  Downloaded libsystemd-sys v0.9.3
  Downloaded mio v1.0.2
  Downloaded uuid v1.10.0
  Downloaded thiserror-impl v1.0.64
  Downloaded slab v0.4.9
  Downloaded protobuf-parse v3.6.0
  Downloaded mapped_futures v0.1.12
  Downloaded clap v4.5.20
  Downloaded tokio-rustls v0.25.0
  Downloaded tempfile v3.13.0
  Downloaded signal-hook-registry v1.4.2
  Downloaded strsim v0.11.1
  Downloaded bitflags v2.6.0
  Downloaded socket2 v0.5.7
  Downloaded smallvec v1.13.2
  Downloaded rustls-native-certs v0.7.3
  Downloaded spin v0.9.8
  Downloaded flume v0.11.0
  Downloaded crossterm v0.28.1
  Downloaded tokio-macros v2.4.0
  Downloaded proc-macro2 v1.0.87
  Downloaded anstyle-parse v0.2.5
  Downloaded systemd v0.10.0
  Downloaded aho-corasick v1.1.3
  Downloaded ryu v1.0.18
  Downloaded rustls-pemfile v2.2.0
  Downloaded serde_derive v1.0.210
  Downloaded syn v2.0.79
  Downloaded indexmap v2.6.0
  Downloaded rumqttc v0.24.0
  Downloaded protobuf-codegen v3.6.0
  Downloaded unicode-ident v1.0.13
  Downloaded rustls v0.22.4
  Downloaded futures-util v0.3.31
  Downloaded hashbrown v0.15.0
  Downloaded regex-syntax v0.8.5
  Downloaded clap_builder v4.5.20
  Downloaded serde_json v1.0.128
  Downloaded rustix v0.38.37
  Downloaded protobuf v3.6.0
  Downloaded rustls-webpki v0.102.8
  Downloaded regex-automata v0.4.8
  Downloaded regex v1.11.0
  Downloaded libc v0.2.159
  Downloaded tokio v1.40.0
  Downloaded linux-raw-sys v0.4.14
  Downloaded ring v0.17.8
  Downloaded 104 crates (13.7 MB) in 32.25s (largest was `ring` at 4.2 MB)
   Compiling proc-macro2 v1.0.87
   Compiling unicode-ident v1.0.13
   Compiling autocfg v1.4.0
   Compiling libc v0.2.159
   Compiling cfg-if v1.0.0
   Compiling log v0.4.22
   Compiling scopeguard v1.2.0
   Compiling memchr v2.7.4
   Compiling bitflags v2.6.0
   Compiling linux-raw-sys v0.4.14
   Compiling shlex v1.3.0
   Compiling thiserror v1.0.64
   Compiling futures-core v0.3.31
   Compiling rustix v0.38.37
   Compiling parking_lot_core v0.9.10
   Compiling futures-sink v0.3.31
   Compiling pin-project-lite v0.2.14
   Compiling regex-syntax v0.8.5
   Compiling rustls-pki-types v1.9.0
   Compiling anyhow v1.0.89
   Compiling once_cell v1.20.2
   Compiling smallvec v1.13.2
   Compiling protobuf v3.6.0
   Compiling futures-channel v0.3.31
   Compiling cc v1.1.28
   Compiling hashbrown v0.15.0
   Compiling fastrand v2.1.1
   Compiling equivalent v1.0.1
   Compiling untrusted v0.9.0
   Compiling home v0.5.9
   Compiling futures-task v0.3.31
   Compiling either v1.13.0
   Compiling futures-io v0.3.31
   Compiling serde v1.0.210
   Compiling pin-utils v0.1.0
   Compiling rustls v0.22.4
   Compiling pkg-config v0.3.31
   Compiling signal-hook v0.3.17
   Compiling utf8parse v0.2.2
   Compiling build-env v0.3.1
   Compiling aho-corasick v1.1.3
   Compiling anstyle-parse v0.2.5
   Compiling lock_api v0.4.12
   Compiling slab v0.4.9
   Compiling colorchoice v1.0.2
   Compiling bytes v1.7.2
   Compiling subtle v2.6.1
   Compiling is_terminal_polyfill v1.70.1
   Compiling anstyle-query v1.1.1
   Compiling zeroize v1.8.1
   Compiling anstyle v1.0.8
   Compiling rustls-pemfile v2.2.0
   Compiling openssl-probe v0.1.5
   Compiling clap_lex v0.7.2
   Compiling indexmap v2.6.0
   Compiling anstream v0.6.15
   Compiling serde_json v1.0.128
   Compiling strsim v0.11.1
   Compiling foreign-types-shared v0.3.1
   Compiling rustls-native-certs v0.7.3
   Compiling quote v1.0.37
   Compiling cstr-argument v0.1.2
   Compiling spin v0.9.8
   Compiling signal-hook-registry v1.4.2
   Compiling getrandom v0.2.15
   Compiling mio v1.0.2
   Compiling socket2 v0.5.7
   Compiling syn v2.0.79
   Compiling libsystemd-sys v0.9.3
   Compiling flume v0.11.0
   Compiling clap_builder v4.5.20
   Compiling parking_lot v0.12.3
   Compiling itoa v1.0.11
   Compiling utf8-cstr v0.1.6
   Compiling ryu v1.0.18
   Compiling uuid v1.10.0
   Compiling signal-hook-mio v0.2.4
   Compiling ring v0.17.8
   Compiling crossterm v0.28.1
   Compiling regex-automata v0.4.8
   Compiling which v4.4.2
   Compiling tempfile v3.13.0
   Compiling clap v4.5.20
   Compiling regex v1.11.0
   Compiling thiserror-impl v1.0.64
   Compiling futures-macro v0.3.31
   Compiling serde_derive v1.0.210
   Compiling tokio-macros v2.4.0
   Compiling foreign-types-macros v0.2.3
   Compiling foreign-types v0.5.0
   Compiling systemd v0.10.0
   Compiling tokio v1.40.0
   Compiling futures-util v0.3.31
   Compiling protobuf-support v3.6.0
   Compiling rustls-webpki v0.102.8
   Compiling futures-executor v0.3.31
   Compiling futures v0.3.31
   Compiling protobuf-parse v3.6.0
   Compiling bisetmap v0.1.6
   Compiling tokio-rustls v0.25.0
   Compiling mapped_futures v0.1.12
   Compiling rumqttc v0.24.0
   Compiling protobuf-codegen v3.6.0
error[E0310]: the parameter type `K` may not live long enough
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mapped_futures-0.1.12/src/mapped_futures/task.rs:104:9
    |
104 |         waker_ref(this)
    |         ^^^^^^^^^^^^^^^
    |         |
    |         the parameter type `K` must be valid for the static lifetime...
    |         ...so that the type `K` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
101 | impl<K: Hash + Eq + 'static, Fut> Task<K, Fut> {
    |                   +++++++++

error[E0310]: the parameter type `Fut` may not live long enough
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mapped_futures-0.1.12/src/mapped_futures/task.rs:104:9
    |
104 |         waker_ref(this)
    |         ^^^^^^^^^^^^^^^
    |         |
    |         the parameter type `Fut` must be valid for the static lifetime...
    |         ...so that the type `Fut` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
101 | impl<K: Hash + Eq, Fut: 'static> Task<K, Fut> {
    |                       +++++++++

For more information about this error, try `rustc --explain E0310`.
error: could not compile `mapped_futures` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by Meisterian** [comment]
Sorry, it seems like the code in master works fine. It is the 0.1.12 version that is not compiling.
Can you release 0.1.13 based on the master branch?

```
cd /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mapped_futures-0.1.12/
vscode ➜ .../registry/src/index.crates.io-6f17d22bba15001f/mapped_futures-0.1.12 $ cargo build
   Compiling mapped_futures v0.1.12 (/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mapped_futures-0.1.12)
error[E0310]: the parameter type `K` may not live long enough
   --> src/mapped_futures/task.rs:104:9
    |
104 |         waker_ref(this)
    |         ^^^^^^^^^^^^^^^
    |         |
    |         the parameter type `K` must be valid for the static lifetime...
    |         ...so that the type `K` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
101 | impl<K: Hash + Eq + 'static, Fut> Task<K, Fut> {
    |                   +++++++++

error[E0310]: the parameter type `Fut` may not live long enough
   --> src/mapped_futures/task.rs:104:9
    |
104 |         waker_ref(this)
    |         ^^^^^^^^^^^^^^^
    |         |
    |         the parameter type `Fut` must be valid for the static lifetime...
    |         ...so that the type `Fut` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
101 | impl<K: Hash + Eq, Fut: 'static> Task<K, Fut> {
    |                       +++++++++

For more information about this error, try `rustc --explain E0310`.
error: could not compile `mapped_futures` (lib) due to 2 previous errors
```

```
git clone https://github.com/StoicDeveloper/mapped_futures.git
Cloning into 'mapped_futures'...
remote: Enumerating objects: 281, done.
remote: Counting objects: 100% (281/281), done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 281 (delta 161), reused 220 (delta 106), pack-reused 0 (from 0)
Receiving objects: 100% (281/281), 82.62 KiB | 8.26 MiB/s, done.
Resolving deltas: 100% (161/161), done.
vscode ➜ /tmp $ cd mapped_futures/
vscode ➜ /tmp/mapped_futures (master) $ cargo build
   Compiling proc-macro2 v1.0.60
   Compiling quote v1.0.28
   Compiling unicode-ident v1.0.9
   Compiling autocfg v1.1.0
   Compiling futures-task v0.3.28
   Compiling futures-core v0.3.28
   Compiling serde v1.0.164
   Compiling futures-util v0.3.28
   Compiling pin-utils v0.1.0
   Compiling pin-project-lite v0.2.9
   Compiling slab v0.4.8
   Compiling syn v2.0.18
   Compiling bisetmap v0.1.6
   Compiling futures-macro v0.3.28
   Compiling mapped_futures v0.1.12 (/tmp/mapped_futures)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.22s
```

```
rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
```

**Comment by Meisterian** [comment]
```
rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
```

```
cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)
```

I have no problem to clone and build the library. The problem appears when I use it as a dependency. Today I created a  new "hello world" project using:
```
cargo new hello_world --bin
```

Then I modified Cargo.toml  to look like this:
```
[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
mapped_futures = { git = "https://github.com/StoicDeveloper/mapped_futures.git" }
```

Then I tried to build it:
```
cargo build
    Updating git repository `https://github.com/StoicDeveloper/mapped_futures.git`
    Updating crates.io index
  Downloaded pin-utils v0.1.0
  Downloaded futures-task v0.3.31
  Downloaded futures-core v0.3.31
  Downloaded autocfg v1.4.0
  Downloaded pin-project-lite v0.2.14
  Downloaded futures-macro v0.3.31
  Downloaded bisetmap v0.1.6
  Downloaded quote v1.0.37
  Downloaded slab v0.4.9
  Downloaded serde v1.0.210
  Downloaded proc-macro2 v1.0.87
  Downloaded unicode-ident v1.0.13
  Downloaded syn v2.0.79
  Downloaded futures-util v0.3.31
  Downloaded 14 crates (744.0 KB) in 4.47s
   Compiling mapped_futures v0.1.12 (https://github.com/StoicDeveloper/mapped_futures.git#771d7a1e)
error[E0310]: the parameter type `K` may not live long enough
   --> /home/xxxxxxxx/.cargo/git/checkouts/mapped_futures-518eb63088bc7400/771d7a1/src/mapped_futures/task.rs:104:9
    |
104 |         waker_ref(this)
    |         ^^^^^^^^^^^^^^^
    |         |
    |         the parameter type `K` must be valid for the static lifetime...
    |         ...so that the type `K` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
101 | impl<K: Hash + Eq + 'static, Fut> Task<K, Fut> {
    |                   +++++++++

error[E0310]: the parameter type `Fut` may not live long enough
   --> /home/xxxxxxxx/.cargo/git/checkouts/mapped_futures-518eb63088bc7400/771d7a1/src/mapped_futures/task.rs:104:9
    |
104 |         waker_ref(this)
    |         ^^^^^^^^^^^^^^^
    |         |
    |         the parameter type `Fut` must be valid for the static lifetime...
    |         ...so that the type `Fut` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
101 | impl<K: Hash + Eq, Fut: 'static> Task<K, Fut> {
    |                       +++++++++

For more information about this error, try `rustc --explain E0310`.
error: could not compile `mapped_futures` (lib) due to 2 previous errors
```

I tried this in a Debian docker container and in Ubuntu(WSL2) and it fails in the same way on both OS:es.

**Comment by Meisterian** [comment]
I can see that I get other dependency versions than specified in Cargo.toml. Maybe that is the reason why is suddenly failed this Monday.

**Comment by Meisterian** [comment]
Maybe cargo set the static linting differently when it is compiling a dependency?

**Comment by Meisterian** [comment]
> When you use FuturesUnordered, does the same compilation error arise?

No.

**Comment by Meisterian** [comment]
I think that the problem is this commit: https://github.com/rust-lang/futures-rs/commit/4f4b0324d96c2424942292f109af09bbce5c4326#diff-4749c3509fed684159acdaa05f4c30240798a7c201aaa5ecc0e25641b4b6b9d6R81

**Comment by Meisterian** [comment]
I updated the PR making the same changes as FuturesUnordered. This code compiles as a dependency.

**Comment by StoicDeveloper** [comment]
Thanks for the fix! I'll be able to review this and release a new version tomorrow. Because the code from futures-rs fixes unsoundness, all previous versions of this crate will be yanked, leaving 0.13 the only accessible version.

**Comment by Meisterian** [comment]
No problem! Thanks for the library!

**Comment by awused** [comment]
There is probably no need to yank the old versions - if the unsafe code written in this PR is sound, then the previous code was using the unsound version of waker_ref safely. The unsafe code in this PR just reimplements the previous accidentally-unsafe API.

**Comment by StoicDeveloper** [comment]
Thanks for the advice. The old versions will be left up. I have confirmed that this branch passes all tests, without causing any undefined behaviour detectable by Miri, and so the branch has been merged, and published as version 0.1.13.

**Pull request merged**
